baseurl = "/"
languageCode = "en-us"
theme = "wowi42"
paginate = 10

[params]
  contentTypeName = "post"
  themeColor = "green"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = "Wowi42"
    subtitle = "Wowi42: The Angry Nerd! C-Level Engineer strongly opiniated! Only my opinions."
    keywords = ""
    copyright = "DTC"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Wowi42"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "kalvad"
        name = "Kalvad"
        url = "https://kalvad.com"
      [[languages.en.menu.main]]
        identifier = "opaala"
        name = "Opaala"
        url = "https://opaala.com"
#      [[languages.en.menu.main]]
#        identifier = "showcase"
#        name = "Showcase"
#        url = "/showcase"
